/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import { useState } from 'react';
import { Estudios } from './components/Estudios';
import { Inicio } from './components/Inicio';
import { Portafolio } from './components/Portafolio';
import { Servicios } from './components/Servicios';



export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (

    <div className={darkMode ? "dark" : ""} >
      <Head>
        <title>Pedro Venegas Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
      </Head>
      <main className=" bg-white dark:bg-gray-900 transition-colors duration-300 ease-in">

        {/* <NavBar setDarkMode={setDarkMode} darkMode={darkMode} /> */}
        {/* Inicio */}
        {/* ESTUDIOS */}

        <section
          id="inicio"
        >
          <Inicio />

          <Estudios />
        </section>
        {/* PORTAFOLIO */}
        <section id="portafolio">
          <Portafolio />
        </section>
        {/* SERVICIOS */}
        <section
          id="services"
        >
          <Servicios />
        </section>

        <section
          id="contact"
        >
          <h1 className="m-auto font-waterfall text-7xl text-white font-bold">
            Contacto
          </h1>
        </section>

      </main>
      {/* FOOTER */}
      <footer />
    </div>
  )
}
