import Head from 'next/head'
import { useState } from 'react';
import { Inicio } from './components/Inicio';
import { Servicios } from './components/Servicios';
import { Portafolio } from './components/Portafolio';
import { Footer } from './components/Footer';
import { NavBar } from './components/NavBar';

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (

    <div className={darkMode ? "dark" : ""} >
      <Head>
        <title>Pedro Venegas Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white dark:bg-gray-900">

        <NavBar setDarkMode={setDarkMode} darkMode={darkMode} />
        {/* Inicio */}

        <section className="min-h-screen">
          <Inicio />
        </section>
        {/* SERVICIOS */}

        <Servicios />

        {/* PORTAFOLIO */}
        <Portafolio />

      </main>
      {/* FOOTER */}
      <Footer />
    </div>
  )
}
